services:
  livekit:
    image: livekit/livekit-server:latest
    command: ["--dev", "--config", "/etc/livekit.yaml"]
    ports:
      - "7880:7880"
      - "7881:7881"
      - "40000-40100:40000-40100/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
